=== blascojavi/2019daw1/LenguajesMarcas/3Eval/UD 5 XML1/ENTREGABLES/Practica 6.2 ENTREGABLE/Parte1/parte1.dtd
<!ELEMENT editorial (informe)>
<!ENTITY defaultVenta "NO_INFO">

  <!ELEMENT informe (cabecera,datos)>
    <!ELEMENT cabecera (empresa,tipoDocumento,descripcionTipoDocumento,fecha)>
      <!ELEMENT empresa (#PCDATA)>
      <!ELEMENT tipoDocumento (#PCDATA)>
      <!ELEMENT descripcionTipoDocumento (#PCDATA)>
      <!ELEMENT fecha (#PCDATA) >
      
      <!ELEMENT datos (regionNorte,regionCentro,regionSur)>
        <!ELEMENT regionNorte (trimestres)>
        <!ELEMENT regionCentro (trimestres)>
        <!ELEMENT regionSur (trimestres)>
            <!ELEMENT trimestres (trimestre1,trimestre2,trimestre3,trimestre4)>
             <!ELEMENT trimestre1 EMPTY >
             <!ATTLIST trimestre1 numero CDATA #FIXED "1" cantidadVendida CDATA "NO_INFO" >
             <!ELEMENT trimestre2 EMPTY >
             <!ATTLIST trimestre2 numero CDATA #FIXED "2" cantidadVendida CDATA "NO_INFO" >
             <!ELEMENT trimestre3 EMPTY>
             <!ATTLIST trimestre3 numero CDATA #FIXED "3" cantidadVendida CDATA "NO_INFO" >
             <!ELEMENT trimestre4 EMPTY >
             <!ATTLIST trimestre4 numero CDATA #FIXED "4" cantidadVendida CDATA "NO_INFO" >

=== blascojavi/2019daw1/LenguajesMarcas/3Eval/UD 5 XML1/ENTREGABLES/Practica 6.2 ENTREGABLE/Parte1/parte1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE editorial SYSTEM "parte1.dtd">
<editorial>
  <informe>
    <cabecera>
      <empresa>Ediciones Aranda</empresa>
      <tipoDocumento>Informe regional de ventas</tipoDocumento>
      <descripcionTipoDocumento>Informe de ventas para las regiones Norte,centro y
        Sur</descripcionTipoDocumento>
      <fecha>30/12/2009</fecha>
    </cabecera>
    <datos>
      <regionNorte>
        <trimestres>
          <trimestre1 numero="1" cantidadVendida="24000"/>
          <trimestre2 numero="2" cantidadVendida="38600"/>
          <trimestre3 numero="3"/>
          <trimestre4 numero="4"/>
        </trimestres>
      </regionNorte>
      <regionCentro>
        <trimestres>
          <trimestre1 numero="1"/>
          <trimestre2 numero="2" cantidadVendida="16080"/>
          <trimestre3 numero="3" cantidadVendida="25000"/>
          <trimestre4 numero="4" cantidadVendida="29000"/>
        </trimestres>
      </regionCentro>
      <regionSur>
        <trimestres>
          <trimestre1 numero="1" cantidadVendida="27000"/>
          <trimestre2 numero="2" cantidadVendida="31400"/>
          <trimestre3 numero="3" cantidadVendida="40100"/>
          <trimestre4 numero="4" cantidadVendida="30000"/>
        </trimestres>
      </regionSur>
      
    </datos>
  </informe>
</editorial>
